version: "3.9"
services:
  postgres:
    image: postgres:16.1
    env_file:
      - .env
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5444:5432"
    healthcheck:
      test: ["CMD-SHELL", "postgres -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_PORT=6379
      - REDIS_DATABASES=16